# Generated by Django 5.0.4 on 2024-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
