# Generated by Django 5.0.4 on 2024-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_alter_reading_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["owner", "timestamp"], name="sensors_rea_owner_i_1e2073_idx"
            ),
        ),
    ]
